# RabbitMQ configuration file
# ============================================================

# Network
listeners.tcp.default = 5672

# Management
management.tcp.port = 15672
management.tcp.ip = 0.0.0.0

# Default credentials (đã set trong environment)
default_user = admin
default_pass = admin123

# Performance
vm_memory_high_watermark.absolute = 512MB